temporalio/helm-charts

- values.yaml
This change goes together with https://github.com/temporalio/temporal/pull/244
The images of this release are tagged `0.20.0`. Updating helm chart to reference this release's images.
I tested this by deploying to a test k8s cluster and making sure the deployment completed, and that the images that are running is the version that I expect.
Example:
1. install helm chart
```
~/src/temporal-helm-charts $ helm install temporaltest .
NAME: temporaltest
LAST DEPLOYED: Sat Mar 21 15:39:57 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
To verify that Temporal has started, run:
kubectl --namespace=default get pods -l "app.kubernetes.io/instance=temporaltest"
```
2. double-check image tags
```
~/src/temporal-helm-charts $ kubectl get pods
NAME …
```
> helm chart: updating images/tags w the release (`0.20.0`)

- README.md
Based on user feedback (thank you @alexshtin!), mentioning the version of Helm that is required for Temporal Helm Charts.
> README: call out the version of Helm (we require 3.* and tested with 3.1.1)

- README.md
- templates/admintools-deployment.yaml
* Adding TEMPORAL_CLI_ADDRESS to admin tools container. (This makes it unnecessary to pass `--address` param to `tctl` tool).
* Updating the readme to reflect the simplified usage.
This change addresses https://github.com/temporalio/temporal-helm-charts/issues/13
> injecting TEMPORAL_CLI_ADDRESS env var into admin tools container

- README.md
Per @alexshtin feedback, including AWS CLI V2 in the list of prerequisites, and suggesting a `kubectl exec` alternative to using `k9s`. Also minor wording fixes.
> readme: various improvements (aws cli v2, shell into admin tools, wording)

- values.yaml
* updating the tags of temporalio/* images for `0.21.1` release,
* removing unused (for now) section for the web component.
> updating image tags for 0.21.1 release

- Chart.yaml
- templates/server-configmap.yaml
- templates/server-deployment.yaml
- values.yaml
Adding ElasticSearch and Kafka, and corresponding configs, to enable temporal Visibility features.
Test:
```
$ kubectl exec -it services/temporaltest-admintools -- bash -c 'tctl --ns benchtest wf start --tl samples_tl --wt basic-driver --wid NU4l --dt 5 --et 259200 --wrp 1 --if ./test.json'
Started Workflow Id: NU4l, run Id: 7ec9d5fb-1ff4-4c53-b118-0aa014e50e81
...
$ kubectl exec -it services/temporaltest-admintools -- bash -c 'tctl --ns benchtest wf count'
2
$ kubectl exec -it services/temporaltest-admintools -- bash -c 'tctl --ns benchtest wf scan'
WORKFLOW TYPE |             WORKFLOW ID              |                RUN ID                | START TIME | EXECUTION TIME | END TIME  
basic-driver  | NU4l                                 | 7ec9d5fb-1ff4-4c53-b118-0aa014e50e81 | 07:38:57   | …
```
> Enable "visibility" by adding and configuring ElasticSearch and Kafka

- templates/server-configmap.yaml
Replacing hardcoded reference to release name with `{{ .Release.Name }}`, allowing for release names other than "temporaltest". 
(This fixes #24)
(Verified this by successfully installing a new release, named `temporaltest2`)
> Remove hardcoded release name from kafka configs

- templates/server-configmap.yaml
Updating configs generated by helm chart to reflect what is required by temporal services (as of https://github.com/temporalio/temporal/pull/354).
tested to make sure deployments succeed and instance starts up as expected:
```
◉ 23:16:17 [markmark ~/src/temporal-helm-charts] (globalmembership|u) $ helm install temporaltest --set server.image.tag=442819414f639f539228f2217d0465f153d0bbe4 --set server.image.repository=markmark206/server --set admintools.image.tag=442819414f639f539228f2217d0465f153d0bbe4 --set admintools.image.repository=markmark206/admin-tools .
NAME: temporaltest
LAST DEPLOYED: Mon May 11 23:16:20 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
To verify that Temporal has started, run:
kubectl --namespace=default get pods -l …
```
> Update configs: 'server.ringpop' => 'global.membership'

- values.yaml
Default to installing `0.23.0` release of temporal (temporal images tagged `0.23.0`).
> Default to installing temporal v 0.23.0 (temporal images tagged 0.23.0)

- values.yaml
In our current "everything is included" setup, we rely on elastic search for visibility functionality. So re-enabling elasticsearch deployment / configuration by default.
> Install elastic search by default

- values.yaml
- values/values.cassandra.yaml
The helm chart was assigning "consistency:'One'" value to the cassandra section in our config.yaml. This consistency field was never used, and then we recently introduced a strongly typed definition for consistency, which is now causing validation errors on load. This diff fixes up the helm chart.
> Fixes issue where helm chart was assigning incorrectly typed value to the cassandra consistency field

- README.md
The full default "Batteries Included" configuration of Temporal is great for testing Temporal's full functionality, but it also requires a reasonably big cluster (most of our pipelines use clusters that include six `m5a.large` machines). This is all great, but sometimes folks just want to install a working minimal configuration of temporal on minikube on their dev box, a _Tiny Batteries Included_ configuration, if you will. ;)
Updating `README.md` to include a section / command line on deploying a small, but working configuration of temporal: one replica of each of temporal services and Cassandra.
> Add a README section on creating a tiny but self-contained Temporal k8s installation

- README.md
- templates/server-configmap.yaml
- templates/server-deployment.yaml
- values.yaml
- values/values.dynamic_config.yaml
This diff presents helm configuration change that allows users to provide and modify dynamic config properties for the k8s cluster.
In order to modify property values user would simply go to `values.yaml` file and change property value to their liking and then they could run `upgrade` command in order to propagate changes.
New properties would have to be added to the `templates/server-configmap.yaml` into dynamic_config.yaml section.
> Using dynamic config in helm

- values/values.dynamic_config.yaml
This should address the failure that we see on CI:
https://tinycicd.temporal.io/teams/main/pipelines/nightly-cassandra-es-byoe/jobs/run-tests/builds/67#L5f2bca35:351
> Fix indentation in the dynamic config

- Chart.yaml
- values.yaml
Updating helm chart version and the tags of the temporal images to default to deploying temporal release 0.29.0.
> Default to deploying temporal 0.29.0

- values/values.antiaffinity.yaml
- values/values.resources.yaml
keep replicas of the same temporal services from running on the same node and include arbitrary but small resource requests to help spread
> add values for improving pod scheduling

- templates/server-job.yaml
- values.yaml
- values/values.cassandra.yaml
Allow for configuring Cassandra replication factor. Example:
```
$ helm install temporaltest --set cassandra.config.cluster_size=5 --set server.config.persistence.default.cassandra.replicationFactor=3 --set server.config.persistence.visibility.cassandra.replicationFactor=3 --set server.replicaCount=3 . --timeout 15m
```
Side note:
With this change, when running the example above, it takes longer for the Cassandra cluster to reach full availability –– now **3** instances of Cassandra need to be online before data could be inserted, as opposed to just one.
During my testing I noticed that the longer Cassandra "time to full availability" started triggering frequent "table {schema_version | schema_update_history} already exist" failures.
The ability to create keyspaces and tables comes online …
> Configure cassandra replication factor

- values.yaml
Relevant documentation here: https://thelastpickle.com/blog/2019/01/30/new-cluster-recommendations.html
Relevant text:
"When the initial work on vnodes in Cassandra was started on the mailing list, 256 tokens was chosen in order to ensure even distribution. This carried over into CASSANDRA-4119 and became part of the implementation. Unfortunately, there were several unforeseen (and unpredictable) consequences of choosing a number this high. Without spending a lot of time on the subject, 256 can cause issues with bootstrapping new nodes (lots of SSTables), repair takes longer, and CPU usage is overall higher. Since Cassandra 3.0, we’ve had the ability to allocate tokens in a more predictable manner that avoids hotspots and leverages the advantage of vnodes. We thus recommend using a value …
> Set number of tokens on Cassandra cluster from 256 (default) to 4

- values/values.antiaffinity.yaml
to prevent temporal services from running on nodes with datastores
and some other services.
> add more antiaffinity rules

- values/values.antiaffinity.yaml
- Switches from "required" to "preferred" (with weights) so that the helm chart can still deploy on smaller clusters
- Fixes bug where matchExpressions are assumed to be ANDs (meaning both conditions had to be met for a pod not to be plaed on a node), when the intent was that they were meant to be ORs.
Validated with a private environment which at least ensures that temporal and cassandra nodes are never co-located.
> Fix anti affinity issue

- values/values.antiaffinity.yaml
Previous check-in got a bit too fancy and we still ended up with too many cassandra nodes co-located with temporal server nodes. This addresses that problem.
> Simplifies anti-affinity configuration

- templates/server-deployment.yaml
The Temporal Worker does not open a port for incoming gRPC calls. Therefore, any liveness probes by K8S which attempt to open a TCP socket to the Worker fail. This causes k8s to periodically recycle the Worker Pod because it thinks it is unhealthy.
This PR removes the liveness probe for Worker roles so that kubernetes doesn't unnecessarily recycle them.
There is a separate PR to add a more proper liveness/health check mechanism for the Worker container in the future
> Remove Liveness Probe from Helm Chart for Temporal Worker

- templates/server-deployment.yaml
Users should be able to run clusters with version check feature disabled.
This can be done by providing `--set server.versionCheckDisabled=1` to helm install command.
> Add a flag for disabling version check

- README.md
Fixing a typo, using better words, using an actual release name (`1.1.0`) in a command line example .
> Minor wording tweaks

- templates/web-deployment.yaml
Service's can reach each other without FQDN
Removed not needed `svc.cluster.local` suffix as it prevents using custom k8s cluster's domains.
> Fix TEMPORAL_GRPC_ENDPOINT value

- templates/server-service-monitor.yaml
- values.yaml
servicemonitor relabeling was mispelled and applied to metric relabeling - added an example of relabeling to the disabled service monitor
> Add example of metricRelabelings and fix helm chart template

- README.md
- templates/server-configmap.yaml
- templates/server-deployment.yaml
- templates/server-dynamicconfigmap.yaml
- Splits the singular ConfigMap into two separate ConfigMaps.
- Mounts the dynamic_config.yaml file onto a separate read-only volume that can detect configuration change updates on the fly.
- Changes the default configuration to search for the dynamic_config.yaml file in the newly mounted volume.
- Updates README instructions.
Validated with private deployment
> Splits Dynamic Config file mount into a separately mounted ConfigMap volume 

- templates/server-configmap.yaml
Recently, a change was added to only condition supply the kafka configuration section if kafka is enabled or kafka is external.
Unfortunately, for existing deployments in production that rely on this helm chart and rely on an external kafka, if they were to simply deploy this updated helm-chart version, Temporal gets stuck in a CrashLoop state because advanced visibility is enabled, but the Kafka section is missing.
Someone who is using external kafka would have to consciously also set the kafka.external value to true to avoid this, which is a breaking change on existing deployments. So instead, we will have a variable that one has to explicitly set in order to omit the Kafka configuration. Existing users are not impacted, and others can opt-in if they don't want the kafka section. …
> Fixes breaking change on kafka configuration block in server-configmap

- templates/server-deployment.yaml
- templates/server-service.yaml
based on chart name (temporal) and service (frontend,matching,history,worker)
this is used in some 3rd party tooling and might be beneficial to others as well.
> add prometheus job name

- README.md
- values.yaml
- values/values.aurora-mysql.yaml
Changesets:
- Add example for Aurora MySQL using connectAttributes
- Add note in README about MySQL <5.7.20
> Summary: Fixes #110 for AWS MySQL Aurora Support

- templates/server-service-monitor.yaml
Fixes YAML indentation that was broken since #92
```
Error: YAML parse error on temporal/templates/server-service-monitor.yaml: error converting YAML to JSON: yaml: line 19: could not find expected ':'
```
> Fix yaml parsing error

- templates/_helpers.tpl
- templates/server-configmap.yaml
- values/values.ndc.yaml
existing template before this PR and after this PR does not show significant changes (except default ports):
```zsh
helm template -f values/values.postgresql.yaml temporaltest \
--set elasticsearch.enabled=false \
--set server.config.persistence.default.sql.user=postgres \
--set server.config.persistence.visibility.sql.user=postgres \
--set server.config.persistence.default.sql.password="$POSTGRES_PASSWORD" \
--set server.config.persistence.visibility.sql.password="$POSTGRES_PASSWORD" \
--set server.config.persistence.default.sql.host=postgresql.default.svc.cluster.local \
--set server.config.persistence.visibility.sql.host=postgresql.default.svc.cluster.local . --timeout 900s
```
NDC configuration can be generated with no error
```zsh
helm template \
-f values/values.postgresql.yaml \
-f …
```
> Add NDC config

- Chart.yaml
* The dependent charts are no longer being served from
old stable repo. Update them to the current functional
URLs.
* Versions are unchanged for compatibility
> Replace deprecated stable chart repo with current ones

- Chart.yaml
- templates/web-ingress.yaml
- templates/web-service.yaml
Changed the `web-ingress` and `web-service` templates to adapt the
annotations metadata subsection to match what the [Helm
docs](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#ingress) do.
> Fix indentation of annotations metadata for the `web` templates

- templates/_helpers.tpl
- templates/server-service.yaml
- values.yaml
This change allow to set custom annotations for the frontend service, in my case add an external-dns annotation
The helper is a copied from bitnami common charts so any annotations can be refactored with this method (and add more if they are missing)
fix #116
> Allow custom annotations

- templates/server-job.yaml
I removed database tools from `server` image in https://github.com/temporalio/temporal/pull/1501. `admin-tools` is the right container for database tools.
> Use admin-tools container for cassandra database tool

- templates/server-job.yaml
Because schema job is failing with args which are passed to `tail` in the admin tools image
> Use command instead of args for admintools image

- templates/server-job.yaml
Elasticsearch index won't be created from the image itself after https://github.com/temporalio/temporal/pull/1501 is merged. This new job should create it instead.
> Add Elasticsearch index creation job

- templates/server-job.yaml
Similar to cassandra use `pre-install` hook if external instance of ES is used.
> Use pre-install hook in case of external ES

- templates/server-job.yaml
- values.yaml
Elasticsearch schema directory structure is getting changed at https://github.com/temporalio/temporal/pull/1586.
> Move elasticsearch.version param to match new dir structure

- templates/server-deployment.yaml
Adding security context constraint for the server-deployment [Set to new `temporal` (a non-root user)] .
In current scenario, the server is deployed as `root` user and is not a recommended practice.
1. Closes  https://github.com/temporalio/temporal/issues/1263.
2. Depends on  https://github.com/temporalio/temporal/pull/1814 (this PR needs to be merged for this to work).
3. How was this tested: deployed on test Kubernetes environment.
> Add SCC and have temporal server run as non-root user

- templates/web-deployment.yaml
Fix tolerations & affinity  in web deployment template
Deployment was failing 
```Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template): unknown field "tolerations" in io.k8s.api.core.v1.PodTemplateSpec```
Did the deployment
2. Any docs updates needed?
no
> [Fix] tolerations & affinity in web deployment

- templates/server-service-monitor.yaml
- values.yaml
Signed-off-by: denismaggior8 <denis.maggiorotto@sunnyvale.it>
```diff
diff --git a/values.yaml b/values.yaml
index bc0850f..dacfec4 100644
--- a/values.yaml
+++ b/values.yaml
@@ -24,6 +24,10 @@ server:
serviceMonitor:
enabled: false
interval: 30s
+      # Set additional lables to all the ServiceMonitor resources
+      additionalLabels: {}
+      #  label1: value1
+      #  label2: value2
metricRelabelings: []
```
```diff
diff --git a/templates/server-service-monitor.yaml b/templates/server-service-monitor.yaml
index d1c762e..83deb00 100644
--- a/templates/server-service-monitor.yaml
+++ b/templates/server-service-monitor.yaml
@@ -15,7 +15,7 @@ metadata:
app.kubernetes.io/component: {{ $service }}
app.kubernetes.io/part-of: {{ $.Chart.Name }}
{{- with (default …
```
> fixes issue #215 - By adding additional labels in ServiceMonitor, an invalid manifest ServiceMonitor resource is rendered

- README.md
- templates/server-deployment.yaml
- values.yaml
- values/values.cloudsqlproxy.yaml
This PR extends the helm templates to support sidecar containers. An example for adding a Google cloud sql proxy sidecar is provided.
> support sidecar containers and provide cloudsqlproxy example

- templates/admintools-deployment.yaml
The `admintools` service did not have a valid hostname set for TEMPORAL_CLI_ADDRESS when deployed in a non-default namespace.  The new value for the prepended service name follows the same pattern as the web-deployment.
It didn't work in its current implementation.  From my experience.
1. Closes issue: #158
Deployed a fresh temporal stack from the helm chart, exec'd into the admintools, and ran `tctl namespace list`.  It worked without complaint.
N/A
> Fix TEMPORAL_CLI_ADDRESS for non-default namespace deployments (#158)

- Chart.yaml
- templates/server-job.yaml
- values.yaml
Adds nodeSelector, affinity and tolerations to server-jobs
Multi-arch clusters amd64/arm64 require nodeSelector, and since I was working on it, added the others.
n/a
helm lint 
helm template
n/a
> Add node selector tolerations affinity to jobs

- Chart.yaml
- values.yaml
> Release 1.14.0

- values.yaml
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Set the image tag for elastic to 7.16.2
> Update Elasticsearch to 7.16.2

- templates/_helpers.tpl
- templates/admintools-deployment.yaml
- templates/server-deployment.yaml
- templates/server-job.yaml
- templates/serviceaccount.yaml
- templates/web-deployment.yaml
- values.yaml
Fixes: issue #245
This patch make the changes that need to fix the issue/feature request added in #245  :
* Add option in values.yaml that enable optionaly creating custom
service account, with following properties:
* values.yaml has set with serviceAccount.create to false, so by
default they use kubernetes default service account - this will
make this change backward compatible
* Once serviceAccount.create is marked to true, it use default name
which is temporal.fullname, but can be customized with serviceAccount.name
* Users can add extraAnnotations to add any additional annotations for
service acccounts
* Usually associating k8s service account with public cloud IAM role
is done by adding custom annotation to serviceAccount, so this
will enable users to pass such annotations to …
> Support adding custom service account

- templates/server-service-monitor.yaml
Helm chart was unable to render due to misconfiguration in service monitor value selector for relabelings
> Fix wrong metricRelabeling key in Servicemonitor

- templates/web-ingress.yaml
This is useful when your TLS hosts values have wildcard asterisks so
they aren't confused with YAML anchors. This should be an otherwise
non-functional change.
Without this change, it is not possible to have wildcard asterisks in
these values.
1. Closes n/a
2. How was this tested: we're using a custom version of the Helm chart with this change. We enable Ingress and have a wildcard asterisk and it behaves as expected.
3. Any docs updates needed? Unlikely, this should be expected behavior.
> Add `quote` filter to Ingress TLS hosts

- templates/server-job.yaml
This PR fixes the issue described in Issue #261.
It prevents setting up temporal with an existing existing secret to bootstrap a cassandra cluster's schemas.
1. Closes #261 
```
helm template temporal . \
--values values/values.cassandra.yaml \
--set server.config.persistence.default.cassandra.existingSecret=someExistingSecret \
--set server.config.persistence.visibility.cassandra.password=aPasswordInstead
--set schema.setup.enabled=true \
--set schema.update.enabled=true 
```
- none
> Respect configured existingSecret in schema setup/update jobs [Issue #261]

- templates/server-job.yaml
This PR fixes the bug described in issue #264 
The `schema-setup` job will not render its `init-containers` when provided with an external Cassandra cluster (`cassandra.enable=false` set in the chart)
1. Closes #264
```
helm template temporal . --values values/values.cassandra.yaml --set schema.setup.enabled=true
```
Before the fix, init-containers are missing, after the fix they are correctly rendered.
- none
> Render schema-setup job's init-containers when using external Cassandra cluster

- Chart.yaml
- templates/web-ingress.yaml
Upgraded some objects to meet current Kubernetes versions.
Per #115, the helm charts no longer work on Kubernetes 1.22+
1. Closes #115 
Deployed on a 1.22 cluster. Note that I was only able to test that the `Ingress` resource was successfully created; I don't have a running Ingress controller at this time to see if it's actually functional.
Likely not. Probably should deprecate Kubernetes<1.19 by now.
> Bugfix #115 kubernetes 1.22 support

- templates/admintools-deployment.yaml
- templates/server-deployment.yaml
- templates/web-deployment.yaml
- values.yaml
This is a relatively minor quality-of-life change that I asked about in Slack and got a positive response about.
This PR adds the ability to add custom labels to the deployment specs, so that pods all launch with them. It supports adding labels to the pods in the cluster itself (by service type, as well as globally), the web UI pods, and the admintools pod.
In my case, we control how log output is parsed through pod labels, and adding labels to tell our log aggregator to parse temporal's logs as JSON was a required step. Other use-cases might be adding tags from deployment systems noting who triggered the deployment, or other bookkeeping tasks.
I ran this PR through `helm template -f values.yaml .` and confirmed no change to the output from previous, then added …
> add custom pod label options to chart

- values.yaml
Now using a specific repo branch to ensure stable URLs for helm chart to reference.
> Fix dashboard references.

- templates/admintools-deployment.yaml
- values.yaml
It's currently not possible to set PodAnnotations on `admintool`, like you can already on the server deployments.
Brings `admintool` to be consistent with the rest of the services. 
- `helm template`
- `helm install` 
`values.yaml` updated appropriately
> Ability to set PodAnnotations on admintools

- templates/web-ingress.yaml
- values.yaml
Hi! Thanks for the good software!
Support custom `ingressClassName`
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
For our use case we use a non-default ingressClassName.
1. Closes 
No issue
I ran `helm template` locally and confirmed that `ingressClassName` worked with or without `.Values.web.ingress.className`.
There was no documentation for value.yaml.
So I wrote an example in value.yaml
> Add support for ingressClassName

- README.md
The link to a discussion about managing Temporal deployments in production in the README is broken.
So I can get to the article without hunting for it.
I clicked the link in preview mode.
> Fix link to discussion about helm charts in production

- Chart.yaml
Bumped elasticsearch chart version to v7.17.3
Getting the error on K8s v1.25:
```
unable to build kubernetes objects from release manifest: resource mapping not found for name: \"elasticsearch-master-pdb\" namespace: \"\" from \"\": no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"\nensure CRDs are installed first"
```
policy/v1beta1 PodDisruptionBudget is deprecated in K8s v1.21+, unavailable in K8s  v1.25+
policy/v1 PodDisruptionBudget should be used instead.
1. Closes 
No
Locally using `Server Version: v1.25.3`.
No
> Bump elasticsearch chart version to v7.17.3

- templates/server-job.yaml
- values.yaml
Removed unreliable not required service check using nslookup
Updated default values elasticsearch image tag version to match Chart dependencies. 
nslookup returns with an exit status of 1 if any query failed and 0 otherwise.
```
% kubectl exec -it temporaltest-admintools-7bf55d4b8f-nhrxb -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:5
% kubectl exec -it temporaltest-admintools-7bf55d4b8f-nhrxb -- bash -c 'set -x; nslookup -type=a -debug elasticsearch-master-headless; echo $?'
+ nslookup -type=a -debug elasticsearch-master-headless
Server:		10.96.0.10
Address:	10.96.0.10:53
Query #2 completed in 10ms:
** server can't find elasticsearch-master-headless.cluster.local: NXDOMAIN
Query #1 completed in 10ms:
** server …
```
> Remove unreliable not required service check using nslookup

- values.yaml
Bumped default server version values to 1.19.0
To match the latest release version.
1. Closes #344
3. How was this tested:
Locally.
4. Any docs updates needed?
Release process update.
> Bump default server version values to 1.19.0

- values/values.postgresql.yaml
This adds more example values to the postgres values file
It took me far too long to figure out these values as the aren't documented and I had look through the source code
It's only commented out/already set default values. But when commenting those then, that's what we use for our deployments
Maybe it would make sense to add this to the docs too, but they are already pretty long and the point you to this file anyway
> add hints for prod deployments

- templates/server-configmap.yaml
Change config template to set up only one visibility store.
Config template is always setting up dual visibility when ES is used for visibility.
1. Closes 
> Fix visibility config in template

- README.md
Added missing `make temporal-sql-tool` command in README.
During my build, I found that the `Install with your own PostgreSQL` stage was missing the method that how to build the temporal-sql-tool.
1. Closes 
None.
3. How was this tested:
Testing on my own device.
4. Any docs updates needed?
Yes. The README.md was changed.
> fix: missing command in README

- templates/admintools-deployment.yaml
- templates/server-deployment.yaml
- templates/web-deployment.yaml
- values.yaml
Ability to have additional environment variable in deployment like so : 
- Globally for server (will be applied to all service deployment)
```yaml
server:
additionalEnv:
- name: "HELLO"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: world
- name: "WORLD"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: hello
```
- For specific services only
```yaml
server:
frontend:
additionalEnv:
- name: "HELLO"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: world
- name: "WORLD"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: hello
```
- For global server + service override
```yaml
server:
additionalEnv:
- name: "HELLO"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: world
- name: "WORLD"
valueFrom:
secretKeyRef:
name: temporal-default-store
key: …
```
> feat: add additional env values

- Chart.yaml
- templates/admintools-deployment.yaml
- templates/server-deployment.yaml
- templates/server-job.yaml
- templates/server-pdb.yaml
- templates/web-deployment.yaml
- values.yaml
* make securityContexts for pod & container configurable everywhere
* add resources config where not possible yet (schema & server-job)
* added configurable topologySpreadConstraints
* added configurable podDisruptionBudget for server components
* removed some blank lines from rendered resources
* current default settings are not changed
* some resources not configurable which is problematic in clusters which enforce some of these settings via policies
1. Closes 
`helm template .`
> make chart more configurable

- values.yaml
Reverted the `replicaCount` change for services made in #365.
Allow inheriting the value from the global config of the `server.replicaCount`.
1. Closes 
No
CICD
No
> Revert services replicaCount to inherit from the global config

- templates/server-secret.yaml
- values.yaml
This is a relatively small change and motivation is same as #280, so directly create a PR.
This PR adds the ability to set custom labels and annotations to the secret resources. It only supports cluster level configuration knob, so users cannot add component level extra labels and annotations to the secret resources.
In our case, we inject sensitive data (e.g. database password) from remote secret store (e.g. [GCP Secret Manager](https://cloud.google.com/secret-manager)) using mutating admission webhook, and adding labels to tell our custom admission webhook to inject sensitive data or not. Other common use-case might be adding annotations to the secret resources and mutate them by [Vault Agent Injector](https://www.vaultproject.io/docs/platform/k8s/injector/annotations). I'm not sure …
> feat: add custom secret label and annotation options to chart

- values.yaml
Bumped default UI version to 2.15.0
To have the most recent UI version.
1. Closes #385
CICD
No
> Bump default UI version to 2.15.0

- templates/server-deployment.yaml
- templates/server-job.yaml
Fixes issue: https://github.com/temporalio/helm-charts/issues/380
Removed the hyphen (`-`) at the beginning of the `include` function. It was causing all whitespaces to be removed from the output resulting in `serviceAccount: ...` to be on the same line as the previous statement.
> fix: disable whitespace removal for include temporal.serviceAccount

- templates/server-deployment.yaml
- templates/server-job.yaml
This PR updates the helm chart to conditionally include the Elasticsearch username and password in the `command` for the `check-elasticsearch`, `check-elasticsearch-index`, and `create-elasticsearch-index` containers. 
These changes were made to allow the helm chart to be used in situations where the Elasticsearch instance does not require authentication. For example Opensearch is in a private network and doesn't have fine-grained auth in place. (If we pass any arbitrary/default username and password we will get 403)
test these changes by deploying the helm chart to a Kubernetes cluster with an Elasticsearch instance that does not require authentication, to ensure that the commands run successfully without the `--user` flag. Additionally, tested by deploying to a …
> feat: add conditional elasticsearch auth in curl commands

- templates/admintools-deployment.yaml
Added new TEMPORAL_ADDRESS env variable
TEMPORAL_CLI_ADDRESS is deprecated and was renamed in the latest Temporal CLI: https://github.com/temporalio/cli/releases/tag/v0.9.0
1. Closes 
No
CICD
No
> Added new TEMPORAL_ADDRESS env variable

- templates/server-configmap.yaml
Added server Prometheus settings conditional configuration.
Support to override server Prometheus settings.
For example, have the ability to change the framework:
```
framework: "opentelemetry"
```
Supported frameworks are: `tally` (the default) or `opentelemetry`.
1. Closes 
No
CICD
No
> Support to configure server Prometheus settings

- templates/server-job.yaml
Do not run the hook that setups the ES schema if not necessary.
Sometimes you don't need to setup the schema if this is done through another process
> Being able to disable the es schema setup job

- templates/server-pdb.yaml
* Added value to name field in PodDisruptionBudget template
PodDisruptionBudget resources require a name field to be present, when utilizing pdb templates, helm upgrade throws the following error.
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource: resource name may not be empty
``` 
When running `helm template . --name-template temporal --values  values.yaml --dry-run` with PDB configured the generated resource does not contain a value for name: and when manually apply the resource (kubectl apply -f pdb.yaml) k8s server throws the following error
```
error: error when retrieving current configuration of:
Resource: "policy/v1, Resource=poddisruptionbudgets", GroupVersionKind: …
```
> FIX Add name value to pdb template

- templates/_helpers.tpl
- templates/server-job.yaml
Automatically create databases and apply the schemas to them for Postgres and MySQL.
Original PR: #281
Allow automatically configuring databases and their schemas.
1. Closes #349
CICD
Tested with MySql & Cassandra environments
No
> Automatically configure Postgres and MySQL databases on startup

- templates/web-deployment.yaml
- values.yaml
Adds the ability to set `additionalVolumes` and `additionalVolumeMounts` to the `web` Deployment.
This was one of many changes needed to support injecting TLS certificates for full mTLS support. Specifically the `web` process needs certificates to talk to the backend services when you enable mTLS.
1. Closes 
We have this chart forked internally and are using it. These changes were applied to it and confirmed it deploys successfully and mounts my volumes:
```yaml
web:
additionalVolumeMounts:
- name: certs
mountPath: /etc/temporal/certs
additionalVolumes:
- name: certs
secret:
secretName: temporal-certs
```
> feat: Add support for `additionalVolumes` and `additionalVolumeMounts` for web

- templates/server-configmap.yaml
Use `visibilityStore` config key instead of `advancedVisibilityStore`
`advancedVisibilityStore` is deprecated.
1. Closes 
> Use visibilityStore config key instead of advancedVisibilityStore

- .github/workflows/publish-charts.yml
This is useful for patch releases on older release lines.
> Allow forcing a specific chart version.

- charts/temporal/Chart.yaml
- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
- charts/temporal/values.yaml
Updated image versions for frontend/matching/worker/history/admintools to 1.23.1
Chart.yaml and values.yaml were out of sync
Not tested 
> Ensure appVersion is used by default as the server image tag.

- charts/temporal/values.yaml
Fix the default type of the image tag from map `{}` to string `""` in the values file.
Issue introduced in https://github.com/temporalio/helm-charts/pull/488
It's causing these errors when rendering the chart
```
coalesce.go:286: warning: cannot overwrite table with non table for temporal.temporal.server.image.tag (map[])
``` 
1. Closes 
None
By rendering helm templates locally
No
> Fix default image tag type in values 

- charts/temporal/templates/serviceaccount.yaml
Added support for pre-upgrade hook for creation of service account.
- While trying to change the service account from default, post install. Service account is not created.
- This is because service account only has pre-install hook, and pre-upgrade is triggered when updating an existing release.
1. Closes #432 
Changes were tested by running a local chart with the existing changes.
No
> fix: add support for pre upgrade.

- charts/temporal/templates/web-service.yaml
Use templating for `web.service` annotations in the same way as `server.service` is defined https://github.com/temporalio/helm-charts/blob/bad8c74311717f2121579f64e2e6b1670fc19818/charts/temporal/templates/server-service.yaml#L15.
A very cool trick to allow passing templated values inside the values.yaml file instead of relying on an outside templating engine
1. Closes 
Added a template in `values.yaml` and ran `helm template`.
No
> Use tplvalues.render for templating inside values

- charts/temporal/templates/server-deployment.yaml
Replaces #308.
Always apply the security context if set rather than only doing so if using cassandra or elasticsearch.
security context is unrelated to persistence engine.
Updated version of #308 which is outdated.
1. Closes 
> Apply security context regardless of persistence engine.

- charts/temporal/templates/server-job.yaml
- charts/temporal/values.yaml
- charts/temporal/values/values.aurora-mysql.yaml
- charts/temporal/values/values.cassandra.yaml
- charts/temporal/values/values.mysql.yaml
- charts/temporal/values/values.postgresql.yaml
This PR adds an ability to skip database creation. The default values ensures that the change will be backwards compatible with an existing installations.
Currently it's not possible to use already existing database when deploying Temporal using this Helm chart
1. Closes #440
I've performed a fresh install with:
```
schema:
createDatabase:
enabled: false
```
> Allow to skip database creation

- charts/temporal/templates/server-job.yaml
- charts/temporal/values/values.postgresql.yaml
Added support for `SQL_TLS*` properties in schema jobs (`server-job.yaml`).
Currently, when PostgreSQL database is secured with TLS, schema jobs are not properly configured.
In the Pull Request we reuse `server.config.persistence.*.sql.tls`, `server.config.additionalVolumes` and `server.config.additionalVolumeMounts` properties..
1. Closes 
No related issues.
No updates needed.
> Configure SQL TLS environment variables in server-job

- charts/temporal/templates/_helpers.tpl
- charts/temporal/values/values.cassandra.yaml
This reverts commit b25c4fcd0e2661d1b18e3bc018ac957d4193448c.
Revert the change to remove the ".cluster.local" suffix.
Just noticed that some of our test cells could not come up after this change.
Our busybox container was not able to resolve cassandra pods without .cluster.local
> Revert "Update Cassandra host URLs to remove the ".cluster.local" suffix (#485)"

- charts/temporal/templates/web-deployment.yaml
- charts/temporal/templates/web-pdb.yaml
- charts/temporal/values.yaml
- added configurable podDisruptionBudget to web component
- added configurable topologySpreadConstraints to web component
- bugfix: topologySpreadConstraints should be of type list instead of map
To enable the web component to have a PodDisruptionBudget created and topologySpreadContraints configured due to the requirement of these configurations being enforced by policy.
1. Closes 
`helm template .`
> Adds a PodDisruptionBudget and topologySpreadConstraints to web

- README.md
> Update README to mention you cannot do Cassandra only anymore.

- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
Elasticsearch plaintext credentials are now escaped to respect password which contains special characters
Without this change it's impossible to use password with specials characters which might be obligatory for some 3rd party managed Elasticsearch solutions.  
E.g. - When using AWS Opensearch you're obliged to use special symbols if using master password istead of IAM auth.
1. Closes #504
We're using custom fork with this change already.
No
> Fix: Quote ES credentials

- charts/temporal/Chart.yaml
Updated Temporal's Helm chart dependencies:
- Grafana from `5.0.10` to `8.0.2`.
- Prometheus from `15.1.3` to `25.22.0`.
While it's a huge bump, I've raised the temporal minor version as it shouldn't be a breaking change in most cases.
Let me know if you prefer to bump the chart's version differently.
Take advantage of products updates while reducing security risks. 
1. Closes 
N/A
```bash
helm template temporal . -n temporal | kubectl apply -f -
```
N/A
> feat: updated grafana and prometheus helm dependencies

- charts/temporal/templates/_helpers.tpl
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
Switch check-cassandra-service init container to use nc. nslookup in recent busybox images is broken and doesn't obey resolv.conf, meaning it won't check k8s search domains.
Alternative fix for #485
> Remove hard coded cluster.local references.

- charts/temporal/templates/_helpers.tpl
- charts/temporal/templates/server-configmap.yaml
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-service.yaml
- charts/temporal/values.yaml
- Enable HTTP API on the frontend
- Expose it on the frontend service
> Enable HTTP API for Nexus

- charts/temporal/templates/server-configmap.yaml
The Env.TEMPORAL_STORE_PASSWORD under sql persistance is quoted in the same way as Env.TEMPORAL_VISIBILITY_STORE_PASSWORD 
Same reasons discussed in https://github.com/temporalio/helm-charts/issues/521, to allow for special characters in the password.
> Quote sql password for default store

- charts/temporal/templates/server-deployment.yaml
The ES check init container on the main deployment of temporal server is made consistent with the Job templates' similar containers.
Problem encountered with setting up Temporal deployment with external Elasticsearch using authentication.
Issue created:
https://github.com/temporalio/helm-charts/issues/529
We need to work a bit to test this chart version with our deployment
> Use admintools-env and secret for ES password consistent with e.g. jobs

- charts/temporal/templates/server-job.yaml
- charts/temporal/values.yaml
This PR addresses the Feature Request #420 
Update the server setup Kubernetes job to create a default namespace.
Create configuration to enable this feature, by default its disabled.
Also, provides option to configure retention period, by default its 3 days.
Creates a default namespace on the server to avoid manual effort.
1. Closes #420 
2. How was this tested:  Manual installation of the helm chart and running the updated job on a Kubernetes cluster to validate creation of new namespace.
`helm lint charts/temporal/.`
`helm install --dry-run temporal charts/temporal/.`
`helm install temporal charts/temporal/.`
4. Any docs updates needed? N/A
> Provide option to create default namespace

- charts/temporal/templates/server-configmap.yaml
- charts/temporal/values.yaml
Config to exclude metrics tags from prometheus.
1. Closes
> Config to specify tags to be excluded in prometheus metrics

- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/admintools-service.yaml
- charts/temporal/templates/frontend-ingress.yaml
- charts/temporal/templates/server-configmap.yaml
- charts/temporal/templates/server-dynamicconfigmap.yaml
- charts/temporal/templates/server-job.yaml
- charts/temporal/templates/server-pdb.yaml
- charts/temporal/templates/server-service.yaml
- charts/temporal/templates/serviceaccount.yaml
- charts/temporal/templates/web-deployment.yaml
- charts/temporal/templates/web-ingress.yaml
- charts/temporal/templates/web-pdb.yaml
- charts/temporal/templates/web-service.yaml
Some call sites used . which was sometimes not the global context.
Changed include calls to use `$` instead of `.` to ensure they pass the global scope.
In some cases `.` wasn't the global scope, causing helpers to fail. In either case it's better to be more explicit about what is being passed.
1. Closes 
> Ensure we use global for includes.

- charts/temporal/templates/server-job.yaml
This PR fixes a YAML parse error on temporal/templates/server-job.yaml (`error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context`).
This error is introduced in release [temporal-0.46.0](https://github.com/temporalio/helm-charts/releases/tag/temporal-0.46.0) and occurs when any `serviceAccount.name` is set.
After upgrading to release 0.46.0 or higher our installation failed, because we are using a custom service account name.
`helm install -f values.yaml --set serviceAccount.name=default debug . --dry-run --debug`
2. Any docs updates needed?
No.
> Fix YAML parse error when specifying service account name

- charts/temporal/templates/_helpers.tpl
This PR fixes a YAML parse error on temporal/templates/server-deployment.yaml (`error converting YAML to JSON: yaml: line 31: mapping values are not allowed in this context`).
This error is introduced in PR #539 and occurs when two or more resource labels (e.g. podLabels) are specified. It works with 1 resource label, because the parse error is caused by missing newlines after each label in the `$resourceLabels` range. This starts to become a problem with at least 2 items.
`helm install -f values.yaml --set additionalLabels.additionalLabel1="additionalTest1"  --set server.frontend.podLabels.label1="test1" --set server.frontend.podLabels.label2="test2" debug . --dry-run --debug`
2. Any docs updates needed?
No.
> Fix YAML parse error when specifying two or more resource labels

- README.md
- charts/temporal/Chart.yaml
- charts/temporal/values.yaml
- charts/temporal/values/values.antiaffinity.yaml
- charts/temporal/values/values.postgresql.yaml
Removed Grafana dependency and related config.
Configuration & installation of monitoring tools is a cluster-level consideration, and shouldn't be specified in an application such as this.
1. Closes #518 
Diff between `helm template` main and this branch has no differences.
Note - if running `helm` from the directory or source, and if you don't run `helm dependencies update`, then helm will want to install grafana since it's enabled by default. 
README is updated.
This will be a breaking change for folks who have grafana enabled, since it will delete their temporal-installed-grafana.
> Remove grafana dependency

- README.md
- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/web-deployment.yaml
- charts/temporal/values.yaml
Added option to pass secret name which will be mouted as env variables in the contianer. 
This will help in scenarios like SSO integration or other conifgurations.
1. Closes 
https://github.com/temporalio/helm-charts/issues/236
Using helm render locally.
Added `Enable SSO in Temporal UI` section in README.md
> Refactor deployment templates to support additional env vars from Secret

- charts/temporal/templates/server-configmap.yaml
Added TLS config to elasticsearch.
I need this for mTLS elasticsearch.
1. Closes #606 
I am using it in my deployment. 
n/a
> elastic-tls: add the elastic tls config if it exists.

- charts/temporal/templates/_helpers.tpl
- charts/temporal/tests/deployment_test.go
This PR adds support for array strings as annotations and labels.
Annotations and labels with array string as value (e.g. `ad.datadoghq.com/temporal-web.logs: '[{"source":"temporal","service":"temporal-web"}]'`) results in an error, both on installation and upgrade.
Error message: 
`Error: UPGRADE FAILED: cannot patch "temporal-admintools" with kind Deployment:  "" is invalid: patch: Invalid value: "{...}": json: cannot unmarshal array into Go struct field ObjectMeta.spec.template.metadata.annotations of type string`
Automated.
Or manual via:
`helm install -f values.yaml --set web.podAnnotations.arrayannotation='[{"test":"true"}]' debug . --dry-run --debug`
2. Any docs updates needed?
No.
> Print annotation and label value as YAML to support array string values

- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/server-job.yaml
- charts/temporal/tests/server_job_test.yaml
Added the admintools.additionalInitContainers to the schema jobs. Swapped some server settings for admintools variants. Removed affinity.
The job runs the admintools container and so those settings seem more appropriate than server. Affinity shouldn't be relevant to a short lived job.
> Switch job to use admintools settings, not server

- charts/temporal/templates/_helpers.tpl
- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/server-configmap.yaml
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
- charts/temporal/templates/server-pdb.yaml
- charts/temporal/templates/server-service-monitor.yaml
- charts/temporal/templates/server-service.yaml
- charts/temporal/values.yaml
Adds support for internal-frontend which has been available since v1.20
Because it is necessary for certain auth configurations to allow internal access, also addresses #560
> Add support for internal-frontend

- charts/temporal/templates/server-job.yaml
One line in the `charts/temporal/templates/server-job.yaml` file inadvertently had tabs instead of spaces, due to a mistake I made when resolving a merge conflict related to PR #602.
When resolving a merge conflict, my editor used tabs instead of spaces in the YAML file.
> fix whitespace

- charts/temporal/templates/server-job.yaml
Fixing the reference to a global Helm value within a local scope
This change would fix an error that occurred in version `0.53.0` of the Helm chart :
```
Error: template: temporal/templates/server-job.yaml:148:40: executing "temporal/templates/server-job.yaml" at <.Values.server>: nil pointer evaluating interface {}.server
```
1. Closes [616](https://github.com/temporalio/helm-charts/issues/616)
Run this helm command and see that the error no longer appears: 
```bash
cd charts/temporal
helm template ./ --set server.config.namespaces.create=true
```
> Fixing the reference to a global Helm value within a local scope

- charts/temporal/templates/server-service.yaml
The frontend-internal service will point to the corresponding internal-frontend pods 
When the internalFrontend is enabled its corresponding service points to the frontend pods instead of the internal-Frontend pods.
Tested locally
> Fix internalFrontend service selector labels

- charts/temporal/values.yaml
- charts/temporal/values/values.aurora-mysql.yaml
change "mysql" driver in values.yaml and example values.aurora-mysql.yaml to "mysql8"
"mysql" is no longer in the list of supported drivers (cassandra, mysql8, postgres12, postgres12_pgx, elasticsearch)
1. Closes 
This is a small change so I don't open an issue for it.
3. How was this tested:
I deployed the helm chart, using sql as default/visibility DB.
4. Any docs updates needed?
No, README doesn't contain this part.
> change mysql driver to mysql8 as mysql is no longer supported

- charts/temporal/templates/web-deployment.yaml
Modified the web-deployment.yml to specify a liveliness probe on the web component monitoring the http port.
Note: didn't add startup or readiness since the other components don't have these either.
Improved monitoring of the web component.
1. Closes https://github.com/temporalio/helm-charts/issues/591
(only if you don't care about the readiness and startup probes)
Used 'kubectl describe' on the web container to verify changes. 
Decreased initialDelaySeconds with a bad tcpSocket port to verify error condition.
Fixed the port to verify there's a Liveliness section in the description and no errors.
No
> Added liveliness probe to the web deployment.

- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-service.yaml
Fix ports for service and enable Istio support out-of-the-box.
1. Closes https://github.com/temporalio/helm-charts/issues/338
Tested on cluster with Istio enabled and strict mTLS.
> Fix ports for service and enable istio support out-of-the-box

- charts/temporal/templates/admintools-deployment.yaml
- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
- charts/temporal/values.yaml
- charts/temporal/values/values.cloudsqlproxy.yaml
Removed sidecarContainers value.
Swapped some `if` for `with` while I was working on the files to simplify them slightly.
Recent Kubernetes versions have specific support for sidecar via the initContainers field.
https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
1. Closes 
> Remove outdated sidecar support.

- charts/temporal/templates/server-job.yaml
Added ability to specify additional environment variables for the namespace job in `server-job.yaml`
Allows TLS arguments to be passed to commands used by Temporal CLI
1. Closes #640 
- set `server.config.namespaces.create` to true
- add the following to `env` in the `create-{{ $namespace.name }}-namespace` job, at line 153
```yaml
{{- with $.Values.admintools.additionalEnv }} 
{{- toYaml . | nindent 12 }}
{{- end }} 
```
- add any envs under `admintools.additionalEnv`
- run `helm template demo charts/temporal -s templates/server-job.yaml`
- verify that the envs under the create namespace jobs reflect the envs added
None
> Add AdditionalEnvs to Namespace Job

- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-service.yaml
- charts/temporal/tests/server_deployment_test.yaml
- charts/temporal/tests/server_service_test.yaml
Added exclusion for the service, as we have for the deployment.
Prevents prometheus scraping services when it's not wanted, such as users using Datadog.
1. Closes https://github.com/temporalio/helm-charts/issues/647
Added unit tests.
No.
> Turn off service annotations when requested.

- charts/temporal/ci/postgres-es-values.yaml
- charts/temporal/ci/postgres-values.yaml
- charts/temporal/values.yaml
- charts/temporal/values/values.aurora-mysql.yaml
- charts/temporal/values/values.mysql.yaml
- charts/temporal/values/values.postgresql.yaml
Set maxIdleConns in sql values.
We noticed that sql performance will improve significantly if we set maxIdleConns.
If this value is not set, it will be taken as 0 and database connections will be deleted as soon as it becomes idle.
> Set maxIdleConns in values

- charts/temporal/values/values.cloudsqlproxy.yaml
Changing the the gcp proxy example to restartPolicy to be working the way it was intended
Ran into this issue when trying to get our temporal installation to work with gcp sql proxy and postgres.
Use this values file to deploy a temporal instance using sql proxy with a gcp postgres instance
> Fix init containers restart policy

- charts/temporal/templates/server-job.yaml
- charts/temporal/tests/server_job_test.yaml
Fixes https://github.com/temporalio/helm-charts/issues/668 by interpolating `schema.resources` into `create-{{store}}-store` initContainers within the server job deployment.
Having certain initContainers not respect resource definitions, while others do, created inconsistencies in the manifests produced by the chart. 
1. Closes https://github.com/temporalio/helm-charts/issues/668
- Added helm unit test
- `helm unittest .`
> respect resources in create-{{store}}-store server job init containers

- charts/temporal/templates/web-service.yaml
- charts/temporal/tests/web_service_test.yaml
- charts/temporal/values.yaml
Addresses: https://github.com/temporalio/helm-charts/issues/680
This PR adds support for `Values.web.service.clusterIP`, which can be set to `None` to turn the `temporal-web` service into a headless service. 
We need to be able to target the service with an external load balancer, which requires the service to be headless. This small change gives users the capability to convert the service into a headless one.
1. Closes https://github.com/temporalio/helm-charts/issues/680
[x] Added `charts/temporal/tests/web_service_test.yaml` with new unit tests to test the new value.
- Inline comment docs were added above the new value to indicate that it's supported and explain its usage.
> Add Values.web.service.clusterIP to provide headless temporal-web service toggle

- charts/temporal/templates/server-job.yaml
- charts/temporal/templates/server-secret.yaml
- charts/temporal/tests/server_job_test.yaml
- charts/temporal/tests/server_secret_test.yaml
Addresses: https://github.com/temporalio/helm-charts/issues/695
This PR allows the server job manifests to be generated even when `Values.server.enabled: false`. Previously, it was not possible to isolate the server job manifests from the rest of the server Deployments (e.g. History, Matching, Frontend, etc).
Additionally, it updates the logic in the server-secret template to ensure that the secrets manifests are still generated when `Values.server.enabled: false`, but one of the schema jobs is enabled. This ensures that the server job still has access to the DB credential secrets required to operate. 
Running the schema migration jobs is something that we'd like to trigger independently from normal server deployments. Schema migrations are only needed in a couple cases:
1. When setting …
> Decouple server job manifests from Values.server.enabled

- charts/temporal/templates/server-deployment.yaml
- charts/temporal/templates/server-job.yaml
Removes `check-cassandra-service` per https://github.com/temporalio/helm-charts/pull/684#issuecomment-2792971071
> Let's just scrap the check-cassandra-service container? I can't see the value as the check-cassandra container will (correctly) fail until Cassandra is up anyway. -- @robholland https://github.com/temporalio/helm-charts/pull/684#issuecomment-2792971071
1. Closes:
* #659 
* #684
helm lint, helm template, and test deployment on kubernetes v1.28
N/A
> Fix: removes check-cassandra-service

- .github/CODEOWNERS
The `CODEOWNERS` file is invalid because it contains a group name (`devex`) that is non-existent. It was renamed to `selfhosted` some time ago and this PR updates it to match that new name.
> Fixed group name

- charts/temporal/values.yaml
Updated admin tools tag from 1.29.0 to 1.29, non-existent tag
https://hub.docker.com/r/temporalio/admin-tools/tags?name=1.29.0
Because 0.68.0 helm chart release is now broken and unable to pull the admin tools image.
> admintools tag 1.29.0 -> 1.29
