Chart.yaml
To make things work smoother on [minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) "clusters" with limited resources, removing everything but bare necessities.
We will re-introduce things as we add support.
=> removing everything but bare necesssities

README.md
=> readme: fixing wording

Chart.yaml, templates/server-configmap.yaml, templates/server-deployment.yaml, templates/web-deployment.yaml, templates/web-ingress.yaml, templates/web-service.yaml, values.yaml
Adds temporal-web.
Adds `elasticsearch.enabled` option to values.
=> Add Temporal-web and optional Elasticsearch

values.yaml
Adding a data source and a few default dashboards. (This code will change a bit when we switch to "everything is optional model").
This works in conjunction with https://github.com/temporalio/temporal-dashboards
=> Add a few default dashboards

README.md, templates/server-configmap.yaml, templates/server-deployment.yaml, templates/server-job.yaml, templates/server-secret.yaml, templates/server-service-monitor.yaml, templates/server-service.yaml, values.yaml, values/values.cassandra.yaml
Adding the option to Bring Your Own Cassandra (`helm install -f values/values.cassandra.yaml temporaltest .`)
=> Adding the option to BYO Cassandra.

Chart.yaml, README.md, templates/server-configmap.yaml, templates/server-deployment.yaml, values.yaml, values/values.elasticsearch.yaml
Adding the option to Bring Your Own ElasticSearch (`helm install -f values/values.elasticsearch.yaml temporaltest .`)
=> Adding the option to BYO ElasticSearch

Chart.yaml, values.yaml
Default helm chart installations to v0.27.0 release of temporal.
=> Default installations to v0.27.0 release of temporal

Chart.yaml, values.yaml
Pointing helm chart to Temporal v 0.28.0.
=> By default, install Temporal 0.28.0

README.md
Adding a brief description on how to access Grafana dashboards that come with "Batteries Included" installations.
=> Document accessing grafana dashboards

README.md
and add a bring your own everything example
=> change wording against prod to for development

README.md
Minor README cleanup + adding a section on accessing temporal Web UI.
=> README: accessing Web UI, various text tweaks

Chart.yaml, values.yaml
Upgrading images from 1.0.0 to 1.1.0
=> Tagging release v1.1.0 images

templates/server-service-monitor.yaml, values.yaml
so that it works and now has default of empty list
=> fix metrics relabeling template

templates/server-configmap.yaml, templates/server-deployment.yaml, templates/server-service.yaml, templates/web-ingress.yaml, values.yaml
I just went through a deployment of tee chart and found a few enhancements like port naming for istio protocol auto discovery and the need to add some volumes
Also I was having problems with the ingress deploy which seemed better after changing the formatting a bit
=> helm chart enhancements

templates/server-deployment.yaml
they are broken if missing - omit if none specified
=> fix issue with additionaVolumes / Mounts

templates/server-configmap.yaml, values.yaml
For the parity with https://github.com/temporalio/temporal/pull/1284.
=> Add quotes to config_tempate.yaml template

values.yaml
=> fix ports of matching and history service

Chart.yaml, values.yaml
> Thanks for opening a PR to our repos! If it is a significant code change, please make sure there is an
> opened issue where we have accepted the idea before filing this PR.
What was changed:
Updated to reference temporal binaries v1.8.0
Motivation & Context:
Release v1.8.0
Closes issue: 
N/A
=> Release 1.8.0

Chart.yaml, values.yaml
* Release Temporal server v1.8.1
Server release v1.8.1
=> Release v1.8.1

Chart.yaml, values.yaml
Upgraded to Web v1.8.0
New version
1. Closes issue: 
--- (only web itself)
=> Bump Web UI from 1.7.1 to 1.8.0

Chart.yaml, values.yaml
Upgraded to web v1.8.1
New release
1. Closes issue: 
=> Bump Web to v1.8.1

Chart.yaml, values.yaml
Bumps Web to v1.9.1
New patch version
1. Closes issue: 
=> Bump Web to v1.9.1

Chart.yaml, README.md, templates/_helpers.tpl, templates/server-configmap.yaml, values.yaml, values/values.antiaffinity.yaml
Remove kafka and zookeeper as they are not used anymore.
=> Remove kafka and zookeeper

templates/server-job.yaml
1. Join containers to one.
2. Add `post-install` hooks.
=> Fix ES index creation job

Chart.yaml, values.yaml
Bump Web to v1.9.2
New version
1. Closes issue: 
=> Bump Web to v1.9.2

templates/server-configmap.yaml, templates/server-deployment.yaml, templates/server-service-monitor.yaml
Added opentelemetry metrics and prometheus scraper.
test opentelemetry metrics
1. Closes 
N/A
N/A
N/A
=> Configure opentelemetry metrics and scraper

Chart.yaml, values.yaml
Bump Web to v1.10.0
New version of web
1. Closes 
=> Bump Web to v1.10.0 (+fix)

README.md
This change fixes a few typos and adds a minor edit in the top level README.
=> Fix a few README typos

templates/server-job.yaml, values.yaml
Index name was changed in https://github.com/temporalio/temporal/pull/1624.
=> Use underscore in index names

Chart.yaml, values.yaml
=> v1.11.0 release

Chart.yaml, values.yaml
=> bump version to v1.11.1

templates/web-deployment.yaml, values.yaml
- Added the ability to include annotations for the web pod
=> Added podAnnotations to web deployment.

Chart.yaml, values.yaml
Bumped Web UI to v1.11.0
new version
1. Closes 
`docker-compose up -d` in `docker-compose repo`
no
=> Bump Web to v1.11.0

Chart.yaml, values.yaml
=> Release v1.11.4

Chart.yaml, values.yaml
=> Release v1.12.0

README.md, templates/web-configmap.yaml, templates/web-deployment.yaml, values.yaml
Added the ability to configure the temporal web ui's config.yml by using helm values.
because i wanted to configure the web ui by altering values.yml instead of altering the helm-chart directly
* deployed the helm chart to my own kubernetes cluster
* deploy the helm chart to a kubernetes cluster and check the config.yml inside the temporal-web pod
the section https://github.com/temporalio/helm-charts#install-and-configure-temporal can be updated by including web ui config
```
helm install temporaltest \
-f values/values.cassandra.yaml \
-f values/values.elasticsearch.yaml \
--set grafana.enabled=false \
--set prometheus.enabled=false \
--set server.replicaCount=5 \
--set server.config.persistence.default.cassandra.hosts=cassandra.data.hos …
```
=> Ability to configure the temporal web ui with helm values

Chart.yaml, values.yaml
Bump server docker tags to the 1.12.2.
=> Release v1.12.2

Chart.yaml, values.yaml
Bump version to 1.13.1
1. Closes 
=> Release 1.13.1

templates/admintools-deployment.yaml, templates/admintools-service.yaml
=> allowed disable admintools

README.md
=> Update README.md with notes on production usage

templates/server-configmap.yaml, templates/server-deployment.yaml
Use server config for metrics.
Path to per-service metrics config deprecation
1. Closes 
=> Update metrics config to use server config, not per-service

templates/server-configmap.yaml
Updated references to global that were missed by initial test.
Fix chart.
Local run of `helm template`
=> Update missing references

templates/server-job.yaml
=> put or on one line

Chart.yaml, values.yaml
=> Release 1.14.5

Chart.yaml, values.yaml
Update release v1.15.0
Update release v1.15.0
1. Closes 
=> Update release v1.15.0

values.yaml
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
adds a comment to web service setup regarding type setting
=> Add comment for web service type

Chart.yaml, values.yaml
Bumped web to v1.14.0
new version
1. Closes 
=> Bump Web to v1.14.0

values.yaml
Bump version to v1.15.1
Bump version to v1.15.1 for new service patch release
1. Closes 
=> Bump version to v1.15.1

Chart.yaml, values.yaml
Prepare v1.15.2 patch
Prepare v1.15.2 patch
1. Closes 
=> Prepare v1.15.2 patch

Chart.yaml, values.yaml
Bumped Web UI to v1.15.0
new version https://github.com/temporalio/web/releases/tag/v1.15.0
1. Closes 
=> Bump Web UI to v1.15.0

Chart.yaml, values.yaml
=> Release 1.16.0

Chart.yaml, values.yaml
=> Release 1.16.1

Chart.yaml, values.yaml
=> Release 1.16.2

README.md, templates/web-deployment.yaml, values.yaml
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
replaces web v1 with web ui v2
=> replace web ui v1 with v2

Chart.yaml, values.yaml
Temporal image tags
New temporal release
1. Closes 
=> Update Chart for new release

Chart.yaml, values.yaml
Update Temporal server version to 1.17.1.
Release 1.17.1.
=> Release 1.17.1

Chart.yaml, values.yaml
Release v1.17.2. Check https://github.com/temporalio/temporal/releases/tag/v1.17.2 for details.
=> Release 1.17.2

Chart.yaml, values.yaml
Release Temporal server 1.18.0
=> Release 1.18.0

Chart.yaml, values.yaml
=> Release 1.18.1

Chart.yaml, values.yaml
Update server version to 1.18.3
=> Update version to 1.18.3

README.md, templates/server-configmap.yaml, values/values.archival.filestore.yaml, values/values.archival.gcloud.yaml, values/values.archival.s3.yaml
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Adds support for file store, s3, gcloud archival configuration. See updated readme for info
=> Add support for archival

Chart.yaml
=> Update OSS server release 1.19

templates/server-configmap.yaml
- removed harcoded `dcRedirectionPolicy` value from configmap template
- user should be able to change `dcRedirectionPolicy` in `values.yaml`
1. Closes 
=> fix: hardcoded dcRedirectionPolicy parameter in server configmap

Chart.yaml, values.yaml
=> Upgrade OSS to 1.19.1

Chart.yaml, values.yaml
=> Upgrade OSS to 1.20.0

Chart.yaml, values.yaml
=> Release 1.20.1

Chart.yaml, values.yaml
=> Release 1.20.2

README.md
=> Remove NBSP from a cassandra setup-schema command

Chart.yaml, templates/server-configmap.yaml, values.yaml
Added support for custom global metrics tags.
We need custom tags.
1. Closes 
No
CICD
No
=> Enable adding custom metrics tags

Chart.yaml, values.yaml
=> Release 1.20.3

README.md
Updated documentation
Bugfix
1. Closes 
#364 
CI
Updated
=> Update documentation with the correct usage of temporal-sql-tool

Chart.yaml, values.yaml
Updated Temporal version to 1.21.0
The latest version
1. Closes 
No
CICD
No
=> Update temporal version to 1.21.0

Chart.yaml, values.yaml
Updated default Temporal version to 1.21.1
Use the latest release
1. Closes 
No
CICD
No
=> Update Temporal version to v1.21.1

templates/server-job.yaml
Added support for the `mysql8` and `postgres12` drivers
Additional feature support.
1. Closes 
No
CICD
No
=> Add support for the mysql8 and postgres12 drivers

Chart.yaml, values.yaml
Updated default Temporal version to 1.21.2
Use the latest release
1. Closes 
No
CICD
No
=> Update Temporal version to v1.21.2

templates/server-configmap.yaml, values/values.cassandra.yaml
=> Add enchanced faultInjection config

Chart.yaml, values.yaml
Update Temporal Server to v1.21.5
1. Closes 
=> Update Temporal Server to v1.21.5

Chart.yaml, values.yaml
Update Temporal Server to v1.22.0
1. Closes 
=> Update Temporal Server to v1.22.0

templates/server-configmap.yaml, values.yaml
Added a new `server.tls` configuration in `values` to allow defining the full TLS configuration found [here](https://docs.temporal.io/references/configuration#tls).
mTLS support is lacking completely in this chart and requires quiet a bit of changes to get working properly. I have this working locally, but there are a few pieces missing for the whole picture. I am trying to open incremental changes, so please let me know if this is an acceptable approach.
* The `web` Deployment configuration will read the various `TEMPORAL_TLS..` environment variables, which we are using to set the config for the UI
* https://github.com/temporalio/helm-charts/pull/427 adds the ability to mount certificates to the `web` Deployment, which then coupled with `web.additionalEnv` as noted above, allows you to …
=> feat: Add ability to set TLS config on `server` components

Chart.yaml, values.yaml
Bump Temporal Server to v1.22.1
1. Closes 
=> Bump Temporal Server to v1.22.1

Chart.yaml, values.yaml
Bump OSS to v1.22.2
1. Closes 
=> Bump OSS to v1.22.2

Chart.yaml, values.yaml
Bump OSS to v1.22.3
1. Closes 
=> Bump OSS to v1.22.3

Chart.yaml, values.yaml
Bump OSS to v1.22.4
1. Closes 
=> Bump OSS to v1.22.4

README.md, charts/temporal/templates/server-configmap.yaml, charts/temporal/templates/server-deployment.yaml, charts/temporal/templates/server-job.yaml, charts/temporal/values/values.cassandra.yaml
Remove Cassandra visibility support
1. Closes 
=> Remove Cassandra visibility support

charts/temporal/templates/server-job.yaml
Fix remove cassandra visibility setup
1. Closes 
=> Fix remove cassandra visibility setup

.github/workflows/publish-charts.yml, README.md, charts/temporal/templates/admintools-deployment.yaml, charts/temporal/templates/server-deployment.yaml, charts/temporal/templates/server-job.yaml, charts/temporal/values.yaml
Amended the admintools image tag to match the current release. Adjusted the release action to prompt for server, ui and admintools versions separately.
admintools versioning has changed to no longer follow just the server version.
1. Closes 
=> Support new admintools image tag format

charts/temporal/Chart.yaml
=> Remove invalid line.

charts/temporal/templates/_helpers.tpl
=> Service account should be set when present, even if not creating.

charts/temporal/templates/server-configmap.yaml
Fixes #333 and #149.
Context: https://github.com/temporalio/temporal/pull/650
1. Closes 
=> Correct outdated port config.

README.md
Switch to documenting install via the helm repo by default.
The helm repo will always give a release version, which will be more thoroughly tested than what happens to be in `main` when the user clones the repo.
1. Closes #458
=> Update README to use repo.

charts/temporal/templates/server-job.yaml
Check for pgx driver as well as plain postgres driver.
The schema should be created/updated in either case.
1. Closes: https://github.com/temporalio/helm-charts/issues/532
=> Check for pgx driver as well as plain postgres.

charts/temporal/templates/_helpers.tpl, charts/temporal/templates/admintools-deployment.yaml, charts/temporal/templates/admintools-service.yaml, charts/temporal/templates/frontend-ingress.yaml, charts/temporal/templates/server-configmap.yaml, charts/temporal/templates/server-deployment.yaml, charts/temporal/templates/server-dynamicconfigmap.yaml, charts/temporal/templates/server-job.yaml, charts/temporal/templates/server-pdb.yaml, charts/temporal/templates/server-secret.yaml, charts/temporal/templates/server-service-monitor.yaml, charts/temporal/templates/server-service.yaml, charts/temporal/templates/serviceaccount.yaml, charts/temporal/templates/tests/test.yaml, charts/temporal/templates/web-deployment.yaml, charts/temporal/templates/web-ingress.yaml, charts/temporal/templates/web-pdb.yaml, charts/temporal/templates/web-service.yaml, charts/temporal/values.yaml
This PR addresses Issue 519 - https://github.com/temporalio/helm-charts/issues/519
To enable consistency of labels across the temporal helm chart codebase and enable the right selectors, this PR aims to use helper functions to achieve the same. 
1. Closes (https://github.com/temporalio/helm-charts/issues/519)
```
helm install --dry-run temporal .
helm install temporal .
```
N/A
=> Templatize resourceLabels for standardization

.github/workflows/publish-charts.yml
=> Update UI version description

.github/workflows/ci.yml, charts/temporal/.helmignore, charts/temporal/tests/deployment_test.go, charts/temporal/tests/server_deployment_test.yaml
Add some unit tests.
These are more succinct and much faster than the terratest unit tests.
1. Closes 
=> Add some unit tests.

CONTRIBUTING.md
I updated the top-level `CONTRIBUTING.md` file to provide more guidance on community contributions.
Many of the PRs we receive lack clear information about how they were tested, known limitations, or in some cases, the specific problem they solve. By setting more clear expectations around these things, my hope is that we can improve the quality of incoming PRs.
=> Expand CONTRIBUTING file

charts/temporal/templates/web-deployment.yaml, charts/temporal/values.yaml
[helm-charts][web] add additionalInitContainers
_additionalInitContainers_ added to web-deployment.yaml
=> [helm-charts][web] add additionalInitContainers
